---
# tasks file for roles/splunk

- name: Populate service facts
  service_facts:

- debug:
    var: ansible_facts.services['qualys-cloud-agent.service']

- name: Qualys Forwarder Status
  debug:
    msg: Qualys Forwarder Up and Running
  when: ansible_facts.services['qualys-cloud-agent.service'].state == 'running'